[package]
name = "diag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.150"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }

