[package]
name = "diag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
chrono = "0.4.31"
crc = "3.0.1"
deku = "0.16.0"
libc = "0.2.150"
pcap-file = "2.0.0"
thiserror = "1.0.50"

